## 지역 축제 방문객 수 예측 및 축제 기획 지원 시스템

In [29]:
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')

CSV_PATH = Path('./전국문화축제정보.csv')
if not CSV_PATH.exists():
    CSV_PATH = Path('./전국문화축제정보.csv')
print(f'데이터폴더 : {CSV_PATH.resolve()}')

데이터폴더 : C:\Users\Administrator\bigdata2026\bigdata2026-basic\전국문화축제정보.csv

In [30]:
import numpy as np
import pandas as pd

plt.rcParams["font.family"] = "Malgun Gothic"
plt.rcParams["axes.unicode_minus"] = False

In [31]:
df= pd.read_csv(CSV_PATH)
df.head()

,축제명,개최장소,축제시작일자,축제종료일자,축제내용,주관기관명,주최기관명,후원기관명,전화번호,홈페이지주소,관련정보,소재지도로명주소,소재지지번주소,위도,경도,데이터기준일자,제공기관코드,제공기관명,방문객수,행사기간,광역시도,버스정류장수,지하철유무
0,구미라면축제,구미역 일원,2026-11-06,2026-11-08,이색라면 레스토랑 및 `갓 튀긴 라면` 팝업스토어 운영 등,경상북도 구미시,경상북도 구미시,NaN,054-480-2652,https://www.gumiramyun.com/,NaN,NaN,경상북도 구미시 원평동 124-23,36.129403,128.331413,2026-06-16,B551011,한국관광공사,147000.0,3,경북,29735.0,N
1,김천김밥축제,직지문화공원 및 사명대사공원 일원,2026-10-23,2026-10-25,김밥플레이리스트(축하공연)+꼬달이 돌잡이 등,경상북도 김천시,경상북도 김천시,NaN,053-965-0910,https://gimbapcity.kr/,NaN,경상북도 김천시 대항면 황악로 1189-52,경상북도 김천시 대항면 운수리 산44-1,36.103084,127.992908,2026-06-16,B551011,한국관광공사,1187000.0,3,경북,29735.0,N
2,임실N치즈축제,임실치즈테마파크+임실치즈마을+임실읍 일원,2026-10-08,2026-10-11,임실N치즈 쭉쭉늘려 내치즈+디저트 퐁뒤체험+국가대표 임실N치즈 대형 쌀피자,임실N치즈축제제전위원회,임실N치즈축제제전위원회,문화체육관광부+농림축산식품부+한국관광공사+전북특별자치도+전북특별자치도 임실군,063-643-3900,www.imsilfestival.com,NaN,전북특별자치도 임실군 성수면 도인2길 50,전북특별자치도 임실군 성수면 도인리 689,35.633102,127.301258,2026-06-16,B551011,한국관광공사,19000.0,4,전북,13180.0,N
3,여주오곡나루축제,여주 신륵사관광지 일원,2026-10-23,2026-10-25,여주쌀 가마솥 비빔밥+군고구마 기네스+여주 본두리 낙화놀이+여주 흔암리 쌍용거 줄다...,여주세종문화관광재단,경기도 여주시,NaN,031-881-9694,https://www.yjfestival.or.kr/,NaN,경기도 여주시 신륵사길 7,경기도 여주시 천송동 297-1,37.300017,127.656746,2026-06-16,B551011,한국관광공사,240000.0,3,경기,38089.0,Y
4,강동선사문화축제,서울 암사동 유적,2026-10-16,2026-10-18,개폐막식+축하공연+개막 드론쇼+폐막 불꽃쇼+거리퍼레이드+강동선사 노래자랑+자치회관 ...,서울특별시 강동구,서울특별시 강동구,NaN,02-3425-5240,https://www.gdsunsa.com/,NaN,서울특별시 강동구 올림픽로 875 (암사동),서울특별시 강동구 암사동 139-2,37.559854,127.130832,2026-06-16,B551011,한국관광공사,118000.0,3,서울,16980.0,Y

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1300 entries, 0 to 1299
Data columns (total 23 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   축제명       1300 non-null   str
 1   개최장소      1300 non-null   str
 2   축제시작일자    1300 non-null   str
 3   축제종료일자    1300 non-null   str
 4   축제내용      1300 non-null   str
 5   주관기관명     1300 non-null   str
 6   주최기관명     1300 non-null   str
 7   후원기관명     597 non-null    str
 8   전화번호      1208 non-null   str
 9   홈페이지주소    813 non-null    str
 10  관련정보      146 non-null    str
 11  소재지도로명주소  1088 non-null   str
 12  소재지지번주소   1063 non-null   str
 13  위도        1072 non-null   float64
 14  경도        1072 non-null   float64
 15  데이터기준일자   1300 non-null   str
 16  제공기관코드    1300 non-null   str
 17  제공기관명     1300 non-null   str
 18  방문객수      1299 non-null   float64
 19  행사기간      1300 non-null   int64
 20  광역시도      1063 non-null   str
 21  버스정류장수    1063 non-null   float64
 22  지하철유무     1300 non-null   str
dtypes: float64(4), int64(1), str(18)
memory usage: 734.8 KB

In [33]:
df.shape

(1300, 23)

In [34]:
df.isnull().sum()

축제명            0
개최장소           0
축제시작일자         0
축제종료일자         0
축제내용           0
주관기관명          0
주최기관명          0
후원기관명        703
전화번호          92
홈페이지주소       487
관련정보        1154
소재지도로명주소     212
소재지지번주소      237
위도           228
경도           228
데이터기준일자        0
제공기관코드         0
제공기관명          0
방문객수           1
행사기간           0
광역시도         237
버스정류장수       237
지하철유무          0
dtype: int64

In [35]:
missing_ratio = df.isnull().mean() 
missing_ratio

축제명         0.000000
개최장소        0.000000
축제시작일자      0.000000
축제종료일자      0.000000
축제내용        0.000000
주관기관명       0.000000
주최기관명       0.000000
후원기관명       0.540769
전화번호        0.070769
홈페이지주소      0.374615
관련정보        0.887692
소재지도로명주소    0.163077
소재지지번주소     0.182308
위도          0.175385
경도          0.175385
데이터기준일자     0.000000
제공기관코드      0.000000
제공기관명       0.000000
방문객수        0.000769
행사기간        0.000000
광역시도        0.182308
버스정류장수      0.182308
지하철유무       0.000000
dtype: float64

In [36]:
df.describe()

                위도           경도          방문객수         행사기간        버스정류장수
count  1072.000000  1072.000000  1.299000e+03  1300.000000   1063.000000
mean     36.350252   127.495963  2.291278e+05     9.668462  19340.776105
std       1.190030     0.902843  2.339256e+05    35.242568  10901.208012
min      33.166229   126.210182  0.000000e+00  -388.000000   3194.000000
25%      35.435058   126.852393  7.450000e+04     2.000000   9975.000000
50%      36.432565   127.104305  1.640000e+05     3.000000  18483.000000
75%      37.460810   128.300727  2.720000e+05     4.000000  24342.000000
max      38.501678   130.909700  1.191000e+06   388.000000  38089.000000

In [37]:
df.describe(include='all')

,축제명,개최장소,축제시작일자,축제종료일자,축제내용,주관기관명,주최기관명,후원기관명,전화번호,홈페이지주소,관련정보,소재지도로명주소,소재지지번주소,위도,경도,데이터기준일자,제공기관코드,제공기관명,방문객수,행사기간,광역시도,버스정류장수,지하철유무
count,1300,1300,1300,1300,1300,1300,1300,597,1208,813,146,1088,1063,1072.000000,1072.000000,1300,1300,1300,1.299000e+03,1300.000000,1063,1063.000000,1300
unique,1209,1038,501,456,1114,800,631,277,796,452,91,739,731,NaN,NaN,141,230,230,NaN,NaN,17,NaN,2
top,안산국제거리극축제,구리한강 시민공원,2026-10-01,2026-10-11,무대공연+체험부스운영+먹거리 체험+꽃 관람,축제추진위원회,경기도 안산시청,서울특별시 양천구청,031-687-0500,http://www.ayac.or.kr,안양예술공원+ APAP+ 김중업박물관,경기도 구리시 코스모스길14번길 249(토평동),경기도 구리시 토평동 810,NaN,NaN,2026-05-26,B551011,한국관광공사,NaN,NaN,경기,NaN,Y
freq,11,15,20,31,11,24,26,31,28,28,30,17,17,NaN,NaN,72,65,65,NaN,NaN,186,NaN,675
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.350252,127.495963,NaN,NaN,NaN,2.291278e+05,9.668462,NaN,19340.776105,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.190030,0.902843,NaN,NaN,NaN,2.339256e+05,35.242568,NaN,10901.208012,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.166229,126.210182,NaN,NaN,NaN,0.000000e+00,-388.000000,NaN,3194.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.435058,126.852393,NaN,NaN,NaN,7.450000e+04,2.000000,NaN,9975.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.432565,127.104305,NaN,NaN,NaN,1.640000e+05,3.000000,NaN,18483.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.460810,128.300727,NaN,NaN,NaN,2.720000e+05,4.000000,NaN,24342.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.501678,130.909700,NaN,NaN,NaN,1.191000e+06,388.000000,NaN,38089.000000,NaN

In [38]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
축제명,1300,1209,안산국제거리극축제,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
개최장소,1300,1038,구리한강 시민공원,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN
축제시작일자,1300,501,2026-10-01,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
축제종료일자,1300,456,2026-10-11,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN
축제내용,1300,1114,무대공연+체험부스운영+먹거리 체험+꽃 관람,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
주관기관명,1300,800,축제추진위원회,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN
주최기관명,1300,631,경기도 안산시청,26,NaN,NaN,NaN,NaN,NaN,NaN,NaN
후원기관명,597,277,서울특별시 양천구청,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN
전화번호,1208,796,031-687-0500,28,NaN,NaN,NaN,NaN,NaN,NaN,NaN
홈페이지주소,813,452,http://www.ayac.or.kr,28,NaN,NaN,NaN,NaN,NaN,NaN,NaN
관련정보,146,91,안양예술공원+ APAP+ 김중업박물관,30,NaN,NaN,NaN,NaN,NaN,NaN,NaN
소재지도로명주소,1088,739,경기도 구리시 코스모스길14번길 249(토평동),17,NaN,NaN,NaN,NaN,NaN,NaN,NaN
소재지지번주소,1063,731,경기도 구리시 토평동 810,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN
위도,1072.0,NaN,NaN,NaN,36.350252,1.19003,33.166229,35.435058,36.432565,37.46081,38.501678
경도,1072.0,NaN,NaN,NaN,127.495963,0.902843,126.210182,126.852393,127.104305,128.300727,130.9097
데이터기준일자,1300,141,2026-05-26,72,NaN,NaN,NaN,NaN,NaN,NaN,NaN
제공기관코드,1300,230,B551011,65,NaN,NaN,NaN,NaN,NaN,NaN,NaN
제공기관명,1300,230,한국관광공사,65,NaN,NaN,NaN,NaN,NaN,NaN,NaN
방문객수,1299.0,NaN,NaN,NaN,229127.790608,233925.624575,0.0,74500.0,164000.0,272000.0,1191000.0
행사기간,1300.0,NaN,NaN,NaN,9.668462,35.242568,-388.0,2.0,3.0,4.0,388.0
광역시도,1063,17,경기,186,NaN,NaN,NaN,NaN,NaN,NaN,NaN
버스정류장수,1063.0,NaN,NaN,NaN,19340.776105,10901.208012,3194.0,9975.0,18483.0,24342.0,38089.0
지하철유무,1300,2,Y,675,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
df['방문객수'].value_counts()

방문객수
0.0         88
121000.0    11
147000.0     8
228000.0     8
210000.0     8
            ..
25500.0      1
811000.0     1
702000.0     1
49000.0      1
196000.0     1
Name: count, Length: 545, dtype: int64