## 지역 축제 방문객 수 예측 및 축제 기획 지원 시스템

### 데이터 정보 확인 및 결측치 제거

In [1]:
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')

CSV_PATH = Path('data/전국문화축제정보정리_raw.csv')
if not CSV_PATH.exists():
    CSV_PATH = Path('data/전국문화축제정보정리_raw.csv')
print(f'데이터폴더 : {CSV_PATH.resolve()}')

데이터폴더 : C:\Users\Administrator\bigdata2026\Bigdata_Team_Project\data\전국문화축제정보정리_raw.csv

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

plt.rcParams["font.family"] = "Malgun Gothic"
plt.rcParams["axes.unicode_minus"] = False

In [3]:
df_raw= pd.read_csv(CSV_PATH, encoding='utf-8')
df_raw.head()

,축제명,개최장소,축제시작일자,축제종료일자,축제내용,주관기관명,주최기관명,후원기관명,전화번호,홈페이지주소,...,위도,경도,데이터기준일자,제공기관코드,제공기관명,방문객수,행사기간,광역시도,버스정류장수,지하철유무
0,구미라면축제,구미역 일원,2026-11-06,2026-11-08,이색라면 레스토랑 및 `갓 튀긴 라면` 팝업스토어 운영 등,경상북도 구미시,경상북도 구미시,NaN,054-480-2652,https://www.gumiramyun.com/,...,36.129403,128.331413,2026-06-16,B551011,한국관광공사,1175585.0,3,경북,29735.0,N
1,김천김밥축제,직지문화공원 및 사명대사공원 일원,2026-10-23,2026-10-25,김밥플레이리스트(축하공연)+꼬달이 돌잡이 등,경상북도 김천시,경상북도 김천시,NaN,053-965-0910,https://gimbapcity.kr/,...,36.103084,127.992908,2026-06-16,B551011,한국관광공사,1132715.0,3,경북,29735.0,N
2,임실N치즈축제,임실치즈테마파크+임실치즈마을+임실읍 일원,2026-10-08,2026-10-11,임실N치즈 쭉쭉늘려 내치즈+디저트 퐁뒤체험+국가대표 임실N치즈 대형 쌀피자,임실N치즈축제제전위원회,임실N치즈축제제전위원회,문화체육관광부+농림축산식품부+한국관광공사+전북특별자치도+전북특별자치도 임실군,063-643-3900,www.imsilfestival.com,...,35.633102,127.301258,2026-06-16,B551011,한국관광공사,739128.0,4,전북,13180.0,N
3,여주오곡나루축제,여주 신륵사관광지 일원,2026-10-23,2026-10-25,여주쌀 가마솥 비빔밥+군고구마 기네스+여주 본두리 낙화놀이+여주 흔암리 쌍용거 줄다...,여주세종문화관광재단,경기도 여주시,NaN,031-881-9694,https://www.yjfestival.or.kr/,...,37.300017,127.656746,2026-06-16,B551011,한국관광공사,1645496.0,3,경기,38089.0,Y
4,강동선사문화축제,서울 암사동 유적,2026-10-16,2026-10-18,개폐막식+축하공연+개막 드론쇼+폐막 불꽃쇼+거리퍼레이드+강동선사 노래자랑+자치회관 ...,서울특별시 강동구,서울특별시 강동구,NaN,02-3425-5240,https://www.gdsunsa.com/,...,37.559854,127.130832,2026-06-16,B551011,한국관광공사,893591.0,3,서울,16980.0,Y

In [4]:
df_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 1300 entries, 0 to 1299
Data columns (total 23 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   축제명       1300 non-null   str
 1   개최장소      1300 non-null   str
 2   축제시작일자    1300 non-null   str
 3   축제종료일자    1300 non-null   str
 4   축제내용      1300 non-null   str
 5   주관기관명     1300 non-null   str
 6   주최기관명     1300 non-null   str
 7   후원기관명     597 non-null    str
 8   전화번호      1208 non-null   str
 9   홈페이지주소    813 non-null    str
 10  관련정보      146 non-null    str
 11  소재지도로명주소  1088 non-null   str
 12  소재지지번주소   1063 non-null   str
 13  위도        1072 non-null   float64
 14  경도        1072 non-null   float64
 15  데이터기준일자   1300 non-null   str
 16  제공기관코드    1300 non-null   str
 17  제공기관명     1300 non-null   str
 18  방문객수      1063 non-null   float64
 19  행사기간      1300 non-null   int64
 20  광역시도      1063 non-null   str
 21  버스정류장수    1063 non-null   float64
 22  지하철유무     1300 non-null   str
dtypes: float64(4), int64(1), str(18)
memory usage: 734.8 KB

In [5]:
df_raw.shape

(1300, 23)

In [6]:
df_raw.isnull().sum()

축제명            0
개최장소           0
축제시작일자         0
축제종료일자         0
축제내용           0
주관기관명          0
주최기관명          0
후원기관명        703
전화번호          92
홈페이지주소       487
관련정보        1154
소재지도로명주소     212
소재지지번주소      237
위도           228
경도           228
데이터기준일자        0
제공기관코드         0
제공기관명          0
방문객수         237
행사기간           0
광역시도         237
버스정류장수       237
지하철유무          0
dtype: int64

방문객수, 광역시도, 버스정류장수 중 하나라도 결측치인 행은 삭제한다.

In [7]:
df_raw = df_raw.dropna(subset=['방문객수', '광역시도', '버스정류장수'])
df_raw.isnull().sum()

축제명           0
개최장소          0
축제시작일자        0
축제종료일자        0
축제내용          0
주관기관명         0
주최기관명         0
후원기관명       534
전화번호         38
홈페이지주소      355
관련정보        934
소재지도로명주소    212
소재지지번주소       0
위도          120
경도          120
데이터기준일자       0
제공기관코드        0
제공기관명         0
방문객수          0
행사기간          0
광역시도          0
버스정류장수        0
지하철유무         0
dtype: int64

In [8]:
df_raw.describe()

               위도          경도          방문객수         행사기간        버스정류장수
count  943.000000  943.000000  1.063000e+03  1063.000000   1063.000000
mean    36.429907  127.493549  1.133432e+06     7.436500  19340.776105
std      1.073550    0.856950  1.209496e+06    26.311431  10901.208012
min     33.229039  126.210182  0.000000e+00  -388.000000   3194.000000
25%     35.548615  126.862740  6.334450e+05     2.000000   9975.000000
50%     36.462249  127.121037  8.671120e+05     3.000000  18483.000000
75%     37.427615  128.259677  1.355700e+06     4.000000  24342.000000
max     38.501678  129.566532  1.910189e+07   365.000000  38089.000000

행사기간이 음수인 행을 제거한다.

In [9]:
df_raw = df_raw[df_raw['행사기간'] >= 0]
df_raw.describe()

               위도          경도          방문객수         행사기간        버스정류장수
count  943.000000  943.000000  1.061000e+03  1061.000000   1061.000000
mean    36.429907  127.493549  1.135321e+06     7.817154  19351.945335
std      1.073550    0.856950  1.209839e+06    23.363787  10906.224625
min     33.229039  126.210182  1.303590e+05     1.000000   3194.000000
25%     35.548615  126.862740  6.341970e+05     2.000000   9975.000000
50%     36.462249  127.121037  8.680390e+05     3.000000  18483.000000
75%     37.427615  128.259677  1.356407e+06     4.000000  24342.000000
max     38.501678  129.566532  1.910189e+07   365.000000  38089.000000

### 라이브러리 불러오기

In [10]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

In [11]:
df = df_raw[['홈페이지주소','방문객수','행사기간','광역시도','버스정류장수','지하철유무']]
df.head()

                          홈페이지주소       방문객수  행사기간 광역시도   버스정류장수 지하철유무
0    https://www.gumiramyun.com/  1175585.0     3   경북  29735.0     N
1         https://gimbapcity.kr/  1132715.0     3   경북  29735.0     N
2          www.imsilfestival.com   739128.0     4   전북  13180.0     N
3  https://www.yjfestival.or.kr/  1645496.0     3   경기  38089.0     Y
4       https://www.gdsunsa.com/   893591.0     3   서울  16980.0     Y

### 범주형 변수(컬럼) 인코딩

In [12]:
df['지하철유무'] = df['지하철유무'].replace({'Y': 1, 'N': 0}).astype(int) # 지하철역이 있으면 1, 없으면 0

In [13]:
df['홈페이지주소'] = df['홈페이지주소'].notnull().astype(int) # 홈페이지주소가 있으면 1, 없으면 0

In [14]:
df.head()

   홈페이지주소       방문객수  행사기간 광역시도   버스정류장수  지하철유무
0       1  1175585.0     3   경북  29735.0      0
1       1  1132715.0     3   경북  29735.0      0
2       1   739128.0     4   전북  13180.0      0
3       1  1645496.0     3   경기  38089.0      1
4       1   893591.0     3   서울  16980.0      1

In [15]:
df.info()

<class 'pandas.DataFrame'>
Index: 1061 entries, 0 to 1298
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   홈페이지주소  1061 non-null   int64
 1   방문객수    1061 non-null   float64
 2   행사기간    1061 non-null   int64
 3   광역시도    1061 non-null   str
 4   버스정류장수  1061 non-null   float64
 5   지하철유무   1061 non-null   int64
dtypes: float64(2), int64(3), str(1)
memory usage: 64.4 KB

### 학습/평가 데이터 나누기

In [16]:
X = df[['홈페이지주소','행사기간','버스정류장수','지하철유무']]
y = df['방문객수']

In [17]:
X.shape, y.shape

((1061, 4), (1061,))

In [18]:
from sklearn.model_selection import train_test_split

# 4개의 변수값이 결과로 나온다. (X, X, y, y) (홀수 번째 학습용, 짝수 번째 검증용)
# 8(train) : 2(test) 비율로 나눈다. 
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=42)

X_train.shape, X_valid.shape, y_train.shape, y_valid.shape

((848, 4), (213, 4), (848,), (213,))

### 선형 회귀 학습

In [19]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)
print('학습완료')

학습완료

In [20]:
pred = model.predict(X_valid)
print(pred[:5])

[1116312.90762062 1351858.67000907 1453843.4845418  1154019.60767097
  644051.10877947]

In [21]:
model.feature_names_in_ # 학습에 사용한 특성 이름목록

array(['홈페이지주소', '행사기간', '버스정류장수', '지하철유무'], dtype=object)

#### MAE

In [22]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_valid, pred) # 정답과 예측

print(f'{mae:.4f}')

50552.2283

#### MSE

In [23]:
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_valid, pred)

print(f'{mse:.4f}')

4167870087.9345

#### RMSE

In [24]:
from sklearn.metrics import root_mean_squared_error

rmse = root_mean_squared_error(y_valid, pred)
print(f'{rmse:.4f}')

64559.0434

#### R2-score

In [25]:
from sklearn.metrics import r2_score

r2 = r2_score(y_valid, pred)
print(f'{r2:.2f}')

0.99